// Generated by bpmn-to-code
package io.miragon.camunda.order.adapter.camunda;

import java.lang.String;

public final class DeliveryprocessProcessApiV1 {
  public static final String PROCESS_ID = "deliveryprocess";

  public static final class Elements {
    public static final String Event_nextDay = "Event_nextDay";

    public static final String Gateway_1aol7g1 = "Gateway_1aol7g1";

    public static final String EndEvent_DeliveryCompleted = "EndEvent_DeliveryCompleted";

    public static final String Task_DeliverOrder = "Task_DeliverOrder";

    public static final String StartEvent_1 = "StartEvent_1";
  }

  public static final class Messages {
  }

  public static final class TaskTypes {
  }

  public static final class Timers {
    public static final BpmnTimer Event_nextDay = new BpmnTimer("Duration", "P1D");

    public static class BpmnTimer {
      public final String type;

      public final String timerValue;

      BpmnTimer(String type, String timerValue) {
        this.type = type;
        this.timerValue = timerValue;
      }
    }
  }
}
